[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = "src/"
addopts = [
    "--verbose",
    "--doctest-modules",
    "--cov-branch",
    "--cov=hopla",
    "--cov-fail-under=40"]