name: "Continuous Integration"

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9.
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt
          pip install --upgrade --editable .
      - name: Analysing the code with pylint.
        # https://github.com/actions/starter-workflows/issues/636
        run: make lint
      - name: Analysing the code with flake8.
        run: make flake
      - name: Run doctests and unittest with pytest
        run: make unittest

