name: "Continuous Integration"

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        # https://github.com/actions/starter-workflows/issues/636
        run: |
          pylint $(find src -name "*.py" | xargs) --rcfile ./.github/workflows/pylintrc.conf
      - name: Run doctest
        # TODO: apply to all relevant *.py files
        run: |
          pip install --upgrade --editable .
          python -m doctest --verbose src/hopla/cli/groupcmds/get.py
      - name: Run unittest with pytest
        run: |
          pytest src/hopla/tests/




